# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crisp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crisp
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'DLRadioButton', '~> 1.4'
    pod 'SimplePDF’

end
